# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Sreeraag Mohan | Personal Webpage
description:      'Homo sapiens based in Bengaluru, KA.'
url:              http://sreeraagmohan.github.io
baseurl:          /

author:
  name:           'Sreeraag Mohan'